spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost:3306}/${DATABASE_NAME:ecommerce}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        jdbc:
          batch_size: 4
        order_inserts: true
