server:
  port: 8081
spring:
  application:
    name: Ecommerce
  profiles:
    active: dev
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate.connection.provider_disables_autocommit: true
        hibernate.jdbc.batch_size: 5
        hibernate.order_inserts: true
        hibernate.order_updates: true
    open-in-view: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations:
      - classpath:db/migration/common/
